<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGN89wpo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGN89wpo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGN89wpo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGN89wpo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGN89wpo\App_KernelDevDebugContainer([
    'container.build_hash' => 'GN89wpo',
    'container.build_id' => 'faf66169',
    'container.build_time' => 1770462959,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGN89wpo');
