<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOcHqDV1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOcHqDV1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOcHqDV1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOcHqDV1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOcHqDV1\App_KernelDevDebugContainer([
    'container.build_hash' => 'OcHqDV1',
    'container.build_id' => '30db3b72',
    'container.build_time' => 1770479603,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOcHqDV1');
