<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGAtIeY6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGAtIeY6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGAtIeY6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGAtIeY6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGAtIeY6\App_KernelDevDebugContainer([
    'container.build_hash' => 'GAtIeY6',
    'container.build_id' => 'a195cd51',
    'container.build_time' => 1770805454,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGAtIeY6');
